# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('StaffId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('Role', models.CharField(max_length=50)),
                ('SUserName', models.CharField(max_length=50)),
                ('SPassword', models.CharField(max_length=50)),
            ],
        ),
    ]
