# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('ProviderId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ProviderName', models.CharField(max_length=50)),
                ('ProviderType', models.CharField(max_length=50)),
                ('NetworkType', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('ZipCode', models.IntegerField(default=0)),
                ('PhoneNumber', models.IntegerField(default=0)),
                ('PUserName', models.CharField(max_length=10)),
                ('PPassword', models.CharField(max_length=10)),
            ],
        ),
    ]
