# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('PatientId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('PFirstName', models.CharField(max_length=50)),
                ('PLastName', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('ZipCode', models.IntegerField(default=0)),
                ('PhoneNumber', models.IntegerField(default=0)),
                ('PDOB', models.DateTimeField()),
                ('PEmployment', models.BooleanField(default=True)),
                ('PAge', models.IntegerField(default=0)),
            ],
        ),
    ]
