# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('ClaimId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ClaimDate', models.DateTimeField()),
                ('HospitalStartDate', models.DateTimeField()),
                ('HospitalEndDate', models.DateTimeField()),
                ('PatientCoPay', models.IntegerField(default=0)),
                ('ProviderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Provider')),
            ],
        ),
        migrations.CreateModel(
            name='ClaimProcessing',
            fields=[
                ('ClaimProcessingId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Status', models.CharField(max_length=20)),
                ('OpenDate', models.DateTimeField()),
                ('ReviewDate', models.DateTimeField()),
                ('ApprovedDate', models.DateTimeField()),
                ('DenyDate', models.DateTimeField()),
                ('RepealDate', models.DateTimeField()),
                ('RejectDate', models.DateTimeField()),
                ('Notes', models.CharField(max_length=20)),
                ('ClaimId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Claim')),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('ConditionId', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('PolicyId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('PolicyName', models.CharField(max_length=50)),
                ('PolicyDuration', models.IntegerField(max_length=20)),
                ('PolicyType', models.CharField(max_length=50)),
                ('PatientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='ReasonForDenial',
            fields=[
                ('ReasonId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceReceived',
            fields=[
                ('ServiceId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ServiceStartDate', models.DateTimeField()),
                ('ServiceEndDate', models.DateTimeField()),
                ('ServiceName', models.CharField(max_length=20)),
                ('ServiceCost', models.IntegerField(default=0)),
                ('ClaimId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Claim')),
                ('PatientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Patient')),
                ('PolicyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Policy')),
                ('ProviderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Provider')),
                ('ServiceTypeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Service')),
            ],
        ),
        migrations.AddField(
            model_name='condition',
            name='PolicyId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Policy'),
        ),
        migrations.AddField(
            model_name='condition',
            name='ServiceId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Service'),
        ),
        migrations.AddField(
            model_name='claimprocessing',
            name='ReasonId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.ReasonForDenial'),
        ),
        migrations.AddField(
            model_name='claimprocessing',
            name='StaffId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Staff'),
        ),
    ]
