# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20170408_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='PolicyDuration',
            field=models.IntegerField(default=0),
        ),
    ]
